// SPDX-License-Identifier: MIT
#pragma once

#include "CnaStreet/Assets/Image.hpp"
#include "CnaStreet/Render/Material.hpp"

#include "Microsoft/Xna/Framework/Vector3.hpp"

#include <cstddef>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

namespace Microsoft::Xna::Framework::Graphics {
    class GraphicsDevice;
    class Texture2D;
}

namespace CnaStreet {

/// The city's material catalogue. An enum rather than strings: every lookup is
/// on a hot path during scene build, and a typo should be a compile error.
enum class MaterialId
{
    // --- highway ---
    AsphaltMain, AsphaltSide, AsphaltWorn,
    RoadMarking,
    ConcretePaving, TactilePaving, GraniteSetts, GraniteKerb,
    ManholeIron, DrainGrate,
    Grass, Soil,

    // --- façades ---
    BrickRed, BrickBuff, BrickEngineering,
    RenderCream, RenderOchre, RenderSage, RenderGrey, RenderTerracotta, RenderBlue,
    RenderWhite,
    Ashlar, ConcretePanel,
    RoofTile, RoofFelt, RoofZinc,
    Glazing, ShopGlazing, Interior,
    FrameWhite, FrameDark, FrameBronze,
    DoorGreen, DoorRed, DoorBlue, DoorOak,
    ShopFascia, Awning,

    // --- street furniture ---
    PaintedSteelDark, PaintedSteelGrey, PaintedSteelGreen, PaintedSteelBlack,
    GalvanisedSteel, Aluminium,
    SignalHousing, LensRed, LensAmber, LensGreen, LensWalkRed, LensWalkGreen,
    LampGlass,
    SignFaceProhibition, SignFaceWarning, SignFaceInformation,
    SignFaceStreetName, SignFaceStreetNameSide,
    SignFaceParking, SignFacePriority, SignBack,
    HydrantRed, BinBody, CabinetGrey,
    Timber,

    // --- vehicles ---
    CarBody, CarGlass, CarTrim, CarTyre, CarLightRear, CarLightFront, LicencePlate,

    // --- people ---
    Skin, Clothing,

    // --- vegetation ---
    Bark, Foliage, Hedge,

    Count
};

/**
 * @brief Owns every texture and material in the city.
 *
 * Two design decisions do most of the work here.
 *
 * **Neutral textures, tinted materials.** The plaster, painted-metal, fabric and
 * car-paint generators produce a *white* surface: all the pattern, none of the
 * colour. The colour arrives as the material's `baseColour`, so eleven façade
 * colours cost one texture rather than eleven, and a car's paint is one texture
 * for the whole fleet. That is the difference between 40 MB of texture memory
 * and 400 MB, and it costs nothing visually because the pattern really is the
 * same on a green pole and a grey one.
 *
 * **Mip chains built here.** Every texture is uploaded with a full mip chain,
 * generated by box-filtering the source image. Without them a road surface seen
 * at a grazing angle aliases into a shimmering mess, which is the single most
 * obvious artefact in an outdoor scene.
 */
class MaterialLibrary
{
public:
    explicit MaterialLibrary(Microsoft::Xna::Framework::Graphics::GraphicsDevice& device);
    ~MaterialLibrary();

    MaterialLibrary(const MaterialLibrary&) = delete;
    MaterialLibrary& operator=(const MaterialLibrary&) = delete;

    /// Generates and uploads every texture. Reports progress through the
    /// callback so the loading screen can say what it is waiting for.
    void build(std::uint32_t seed);

    [[nodiscard]] const Material& get(MaterialId id) const;
    [[nodiscard]] Material& mutableGet(MaterialId id);

    /// Registers a material derived from one of the catalogue entries — used for
    /// the per-window interior atlas cells, which differ only in UV transform.
    [[nodiscard]] const Material* derive(const std::string& name, MaterialId base,
                                         const Microsoft::Xna::Framework::Vector2& uvScale,
                                         const Microsoft::Xna::Framework::Vector2& uvOffset);

    /// A variant differing only in colour: car paint, clothing, a lit signal
    /// lens. Sharing the textures is the whole point — a fleet of twelve
    /// differently painted cars costs one texture set, not twelve.
    [[nodiscard]] const Material* deriveTinted(
        const std::string& name, MaterialId base,
        const Microsoft::Xna::Framework::Vector3& baseColour,
        const Microsoft::Xna::Framework::Vector3& emissive =
            Microsoft::Xna::Framework::Vector3::Zero);

    /// Registers a material with textures of its own, outside the catalogue.
    /// The shop fascias need this: every shop has a different name baked into
    /// its board, so they cannot share one texture the way the painted metal and
    /// the car paint do. Returns the existing entry when @p name is already
    /// registered, so a repeated house number costs one texture rather than one
    /// per door.
    [[nodiscard]] const Material* add(const std::string& name, const Assets::SurfaceMaps& maps,
                                      Material material);
    /// The material registered under @p name, or nullptr.
    [[nodiscard]] const Material* find(const std::string& name) const;

    /// Every derived material, so the overlay can count them.
    [[nodiscard]] std::size_t derivedCount() const { return derived_.size(); }

    [[nodiscard]] std::size_t textureCount() const { return textures_.size(); }
    [[nodiscard]] std::size_t textureBytes() const { return textureBytes_; }
    [[nodiscard]] std::size_t materialCount() const;

private:
    /// Uploads one linear or sRGB image with a full mip chain.
    Microsoft::Xna::Framework::Graphics::Texture2D* upload(const Assets::Image& image, bool srgb,
                                                           const std::string& name);
    /// Uploads a generated surface's three maps and fills in a material.
    void install(MaterialId id, const std::string& name, const Assets::SurfaceMaps& maps,
                 Material material);

    Microsoft::Xna::Framework::Graphics::GraphicsDevice& device_;
    std::vector<std::unique_ptr<Microsoft::Xna::Framework::Graphics::Texture2D>> textures_;
    std::vector<Material> materials_;
    std::unordered_map<std::string, std::unique_ptr<Material>> derived_;
    std::size_t textureBytes_ = 0;
};

}  // namespace CnaStreet
